// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DoradoB2BCoreContext.Models
{
    public partial class ErrorLog
    {
        [Key]
        [Column("Err_ErrId")]
        public int ErrErrId { get; set; }
        [Column("Err_DataUtwozenia", TypeName = "datetime")]
        public DateTime ErrDataUtwozenia { get; set; }
        [Column("Err_message")]
        public string ErrMessage { get; set; }
        [Column("Err_call_stack")]
        public string ErrCallStack { get; set; }
        [Column("Err_parent_exception")]
        public int? ErrParentException { get; set; }
        [Column("Err_source")]
        public string ErrSource { get; set; }
        [Column("Err_Funcion")]
        public string ErrFuncion { get; set; }
        [Column("Err_Class")]
        public string ErrClass { get; set; }
        [Column("Err_Aplikacja")]
        public int ErrAplikacja { get; set; }
        [Column("Err_FileTextContent")]
        public string ErrFileTextContent { get; set; }
    }
}